# -*- coding: utf-8 -*-
"""Task01-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SgPPxCvvw7y1XGDGOqSLxUWta0xThcoy

# **Code to order**
"""

g.serialize("example1.ttl", format="ttl")

for subj, pred, obj in g:
  print(subj,pred,obj)

g.parse(github_storage+"/rdf/example1.rdf", format="xml")

print(g.serialize(format="ttl"))

print(g.serialize(format="xml"))

g.parse(github_storage+"/rdf/example2.rdf", format="xml")

from rdflib import Graph, Namespace, Literal
g = Graph()

"""# **Task 01: Reading and writing RDF files** (order the code in this section)"""

pip install rdflib

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2026-2027/refs/heads/master/Assignment4/course_materials"

"""Spanish: Para leer y escribir ficheros que contienen tripletas en RDFlib empleamos dos métodos de la librería: parse y serialize. Podemos añadir tripletas a nuestro grafo empleando parse, que leerá el recurso proporcionado. Debemos además indicarle el formato si este no puede ser inferido. El recurso puede ser local o remoto, como en nuestro caso. El resultado es el mismo. Podemos añadir todos los datos que queramos a nuestro grafo, los datos simplemente se irán fusionando.

English: To read and write RDF files that contain triplets we employ two methods from the library: parse and serialize. We can add triplets to our graph using parse, which will read the specified resource. We must also specify the format if it cannot be inferred. The resource can be local or remote, as in our case. The result is the same. We can add as much data as we want to our graph, and the data will simple be merged together.

Spanish:  Ahora podemos comprobar el resultado volcando las tripletas de forma sencilla.

English: We can now check the result by simply outputting the triplets.

Spanish: Ahora podemos ver la operación inversa, serializando estos datos a algún formato que nos lo permita. Este proceso también nos permite una conversión sencilla entre formatos. Hacer primero en ttl y luego en xml.

English: We can now look at the reverse process: serialising this data into a format that allows us to do so. This process also enables us to convert easily between formats. First in TTL, then in XML.

Spanish: También podemos guardar el resultado serializado en un fichero, puedes ver este fichero resultante en el panel izquierdo.

English: We can also save the serialised result to a file; you can view this resulting file in the left-hand pane.

# **Task 01: Do the following exercises**

Spanish: Importar rdf/example1b.rdf

English: Import rdf/example1b.rdf
"""

#TODO

"""Spanish: Leer el grafo en formato json-ld

English: Read the result in json-ld format
"""

#TODO

"""Spanish: Mostrar por pantalla cuántas tripletas tiene el grafo

English: Print how many triples the graph contains
"""

#TODO

"""Spanish: Guardar el grafo en un fichero example1b.nt en formato N-Triples y abrirlo en el panel izquierdo

English: Save the graph to example1b.nt using N-Triples and open it in the left-hand pane
"""

#TODO

"""Spanish: Convertir rdf/example2.rdf de RDF/XML a Turtle sin pasar por disco

English: Convert rdf/example2.rdf from RDF/XML to Turtle without writing to disk
"""

#TODO