# -*- coding: utf-8 -*-
"""Task03-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_T_MUmZCL-wC9lckoEYqIxof1pzNsWu

# **Code to order**
"""

for s,p,o in g.triples((None, VCARD.FN, None)):
  print(o)

#from rdflib import FOAF
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
for s,p,o in g.triples((None, FOAF.email, None)):
  print(s,p,o)

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for s,p,o in g.triples((None, VCARD.FN, None)):
  print(s)

print(Literal(1, datatype=XSD.number).eq(Literal("1", datatype=XSD.string)))
print(Literal(1, datatype=XSD.number).eq(Literal(1, datatype=XSD.string)))
print(Literal(1).eq(Literal(1, datatype=XSD.number)))
print(Literal(1, datatype=XSD.number).eq(Literal(1, datatype=XSD.number)))
print(Literal(1).datatype)
print(Literal("1").datatype)

from rdflib import XSD
for t in g.triples((None, VCARD.Family, Literal('Smith', datatype=XSD.string))):
  print(t)

janeSmithURI = g.value(subject=None, predicate=VCARD.FN, object=Literal("Jane Smith"))
knows = g.triples((None, FOAF.knows, janeSmithURI))

for s,p,o in knows:
  givenName = g.value(subject=s, predicate=VCARD.Given, object=None)
  print(givenName)

"""# **TASK 3: Statement-based query**"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2026-2027/refs/heads/master/Assignment4/course_materials"

"""Spanish: Importamos example3.rdf en nuestro grafo

English: Import example3.rdf in our graph
"""

from rdflib import Graph, Namespace, Literal
g = Graph()

#TODO - Complete
g.(github_storage+"/rdf/", format="")

"""Spanish: Listar todos los recursos con la propiedad VCARD:FN

English: List all resources with the VCARD:FN property

Spanish: Listar el nombre completo (VCARD:FN) de estos recursos

English: List the full name (VCARD:FN) of these resources

Spanish: Listar ahora todos los recursos que tienen el nombre de familia "Smith", debemos tener en cuenta el tipo de dato de nuestro literales a la hora de realizar búsquedas. En nuestro ejemplo los literales están tipados como XSD String (http://www.w3.org/2001/XMLSchema#string) y al buscar debemos indicarlo, de lo contrario la comparación fallará aunque las cadenas de texto sean iguales.

English: Llist all resources with the family name "Smith", we must take into account the data type of our literals when performing searches. In our example, the literals are typed as XSD String (http://www.w3.org/2001/XMLSchema#string) and we must specify this when searching; otherwise, the comparison will fail even if the text strings are identical.

Spanish: Comprobar comparaciones entre literales

English: Check comparisons between literals

Spanish: Listar todos los recursos que contienen un email

English: List all resources that contains an email

Spanish: Listar todos los sujetos que conocen a "Jane Smith" (VCARD:FN) por su nombre de pila (VCARD:Given). Cuando sepamos que vamos a obtener un solo resultado podemos emplear la función value indicando cada parámetro conocido (solo uno debe ser None).

English: List all subjects who know "Jane Smith" (VCARD:FN) by her first name (VCARD:Given). When we know that we will obtain a single result, we can use the "value" function, specifying each known parameter (only one of which must be "None").

# **Task 03: Do the following exercises**

Spanish: Listar todos los recursos cuyo apellido (VCARD:Family) sea "Jones"

English: List all resources whose family name is "Jones"
"""

#TODO

"""Spanish: Averiguar a cuántas personas conoce Matt Jones

English: Find out how many people Matt Jones knows
"""

#TODO

"""Spanish: Comprobar si existe algún recurso con el apellido "García"

English: Check whether any resource has the family name "García"
"""

#TODO

"""Spanish: Comprobar que buscar "Smith" sin indicar el tipo de dato no devuelve nada

English: Check that searching for "Smith" without the datatype returns nothing
"""

#TODO