# -*- coding: utf-8 -*-
"""Task04-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUsI6R6zHCIq-Lk7mx9Opj3u9qbqcPOQ

# **Code to order**
"""

q = prepareQuery('''
  SELECT ?Subject ?Email WHERE {
    ?Subject foaf:email ?Email.
  }
  ''',
  initNs = { "foaf": FOAF}
)

for r in g.query(q):
  print(r.Subject,r.Email)

q = prepareQuery('''
  SELECT  ?Subject ?Given  WHERE {
    ?Subject foaf:knows ?JaneSmith.
	?JaneSmith vcard:FN ?JaneSmithFullName.
	?Subject vcard:Given ?Given.
  }
  ''',
  initNs = { "foaf": FOAF, "vcard": VCARD, "xsd":XSD}
)

for r in g.query(q, initBindings = {'?JaneSmithFullName' : Literal('Jane Smith', datatype=XSD.string)}):
  print(r.Subject, r.Given)

q = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject vcard:FN ?FullName.
  }
  ''',
  initNs = { "vcard": VCARD}
)

for r in g.query(q):
  print(r.Subject)

q = prepareQuery('''
  SELECT ?Subject WHERE {
    ?Subject vcard:Family ?Family.
  }
  ''',
  initNs = { "vcard": VCARD}
)

for r in g.query(q, initBindings = {'?Family' : Literal('Smith', datatype=XSD.string)}):
  print(r.Subject)

q = prepareQuery('''
  SELECT ?Subject ?FullName WHERE {
    ?Subject vcard:FN ?FullName.
  }
  ''',
  initNs = { "vcard": VCARD}
)

for r in g.query(q):
  print(r.Subject, r.FullName)

"""# **Task 04: Graph querying**"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2026-2027/refs/heads/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal
g = Graph()
g.parse(github_storage+"/rdf/example3.rdf", format="xml")

from rdflib.plugins.sparql import prepareQuery
from rdflib import XSD
from rdflib import FOAF

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

"""Spanish: Listar todos los recursos que contienen la propiedad VCARD:FN

English: List all resources that contain the VCARD:FN property

Spanish Repetir la anterior consulta, pero pidiendo ahora además los nombres completos de los sujetos

English: Repeat the previous query, but this time also request the full names of the subjects

Spanish: Obtener todos los recursos que contienen "Smith" como nombre de familia

English: Retrieve all resources containing ‘Smith’ as a surname

Spanish: Obtener todos los elementos que contienen un email asociado

English: Retrieve all items that have an associated email address

Spanish: Consultar todos los que conocen (FOAF:knows) a "Jane Smith" y obtenemos sus nombres de pila (VCARD:Given)

English: Query everyone who knows (FOAF:knows) “Jane Smith” and retrieve their first names (VCARD:Given)

# **Task 04: Do the following exercises**

Spanish: Listar el nombre completo y el email de quienes tengan ambos

English: List the full name and email of those who have both
"""

#TODO

"""Spanish: Listar todos los nombres completos ordenados alfabéticamente (ORDER BY)

English: List all full names in alphabetical order (ORDER BY)
"""

#TODO

"""Spanish: Listar el nombre completo de quienes no tienen email

English: List the fullname of those who do not have an email
"""

#TODO

"""Spanish: Comprobar si existe algún recurso con el apellido "García"

English: Check whether any resource has the surname "García"
"""

#TODO