# -*- coding: utf-8 -*-
"""Task02-puzzle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4-xvz7GPcGCYySjpkU7k87kKOs87Oq6

# **Code to order**
"""

g.add((EX.JaneSmith, VCARD.FN, Literal("Jane Smith")))
g.add((EX.JaneSmith, VCARD.EMAIL, Literal("jsmith@example.org")))

print(g.serialize(format="ttl"))

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

resource = (johnURI, VCARD.FN, fullName)

print(resource)

g.add(resource)

g.add((EX.JohnSmith, FOAF.knows, EX.JaneSmith))

g.namespace_manager.bind('ex', EX)
print(g.serialize(format="ttl"))

fullName = Literal("John Smith")
EX = Namespace("http://example.org/")
johnURI = EX.JohnSmith

from rdflib import FOAF

"""# **Task 02: Managing statements**"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2026-2027/refs/heads/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal
g = Graph()

"""Spanish: Crear el recurso John Smith con su nombre completo

English: Create a resource called "John Smith" using his full name

Spanish: Generar la sentencia añadiendo el predicado (propiedad)

English: Generate the statement by adding the predicate (property)

Spanish: Crear otro recurso para Jane con su nombre completo e email. Se puede abreviar un poco lo que hemos hecho en la tarea anterior, atención a los dobles paréntesis, add() acepta un solo parámetro en forma de tupla, no 3 parámetros.

English: Create another resource for Jane using her full name and email address. We can simplify what we did in the previous exercise a little; note the double parentheses, add() takes a single parameter in the form of a tuple, not three parameters.

Spanish: Añadir una relación entre John y Jane mediante el vocabulario FOAF. Hay ciertos espacios de nombres que son nativos a RDFlib, FOAF es uno de ello y no hace falta que lo declaremos nosotros

English: Add a relationship between John and Jane using FOAF vocabulary. There are certain namespaces that are native to RDFlib; FOAF is one of them, and we do not need to declare it ourselves

Spanish: Vemos el resultado conjunto

English: View the overall result

Spanish: Añadir el prefijo EX en el grafo

English: Add the EX prefix to the graph

# **Task 02: Do the following exercises**

Spanish: Crear el recurso Sarah Jones con su nombre completo (VCARD.FN), nombre de pila (VCARD.Given) y apellido (VCARD.Family)

English: Create a resource for Sarah Jones with her full name (VCARD.FN), given name (VCARD.Given) and family name (VCARD.Family)
"""

#TODO

"""Spanish: Añadir el email de John (jsmith@example.org), que aún no lo tiene

English: Add John's email address (jsmith@example.org), which he does not have yet
"""

#TODO

"""Spansih: Indicar que John y Sarah son personas usando el vocabulario FOAF (FOAF.Person)

English: State that John and Sarah are persons using the FOAF vocabulary (FOAF.Person)
"""

from rdflib import RDF

#TODO
g.add(( , RDF.type, ))
g.add((, RDF.type, ))

"""Spanish: Comprobamos si la tripleta "John conoce a Jane" está en el grafo y comprobamos el número de tripletas. Eliminar la tripleta y volver a comprabarlo. (las tripletas se eiminan con g.remove(...))

English: We check whether the triplet “John knows Jane” is in the graph and count the number of triplets. Remove the triplet and check again. (Triplets are removed using g.remove(...))
"""

print((EX.JohnSmith, FOAF.knows, EX.JaneSmith) in g)
print(len(g))

#TODO

print((EX.JohnSmith, FOAF.knows, EX.JaneSmith) in g)
print(len(g))