# -*- coding: utf-8 -*-
"""task08_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWsw5MMwhv9BJyQsLCpS9oARJr2ctuEq

**Task 08: Completing missing data**
"""

# !pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Spanish: Lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas.

English: List all the elements of the Person class in the first graph (data01.rdf) and fill in any missing fields (given name, family name and email) using the data from the second graph (data02.rdf). You can use SPARQL queries or iterate through the graph, or both.
"""

from rdflib.namespace import RDF

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
DATA  = Namespace("http://data.org#")

FIELDS = [VCARD.Given, VCARD.Family, VCARD.EMAIL]   # given name, family name, email

# List all elements of class Person in the first graph (data01.rdf)
persons_g1 = sorted(set(g1.subjects(RDF.type, DATA.Person)))
print("Persons in g1 (before completion):")
for p in persons_g1:
    print(f"  {p}")


# Fill in the fields missing in g1 with the data from g2 (data02.rdf).
# Both graphs share the same base URI, so a person is identified by
# the same URIRef in g1 and g2.
print("\nCompleting missing fields (given name, family name, email):")
for person in persons_g1:
    for prop in FIELDS:
        if (person, prop, None) not in g1:       # field missing in g1
            value = g2.value(person, prop)       # look for it in g2
            if value is not None:
                g1.add((person, prop, value))
                print(f"  + {person.split('#')[-1]}  {prop.split('#')[-1]} = {value}")
            else:
                print(f"  ! {person.split('#')[-1]}  {prop.split('#')[-1]} -> not found in g2")


# Show the first graph after the completion
print("\nPersons in g1 (after completion):")
for person in persons_g1:
    print(f"\n  {person}")
    for prop in FIELDS:
        for v in g1.objects(person, prop):
            print(f"      {prop.split('#')[-1]}: {v}")