# -*- coding: utf-8 -*-
"""Task_07_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q9LdtEbFaU-ISQDv2CHm5qsBO33TapMe

**Task 07: Querying RDF(s)**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install rdflib
# %pip install oeg-sw-class
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2026-2027-ODKG/master/Assignment4/course_materials"

"""Spanish: Primero leemos los ficheros RDF

English: First let's read the RDF file
"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
from oeg_sw_class import Report
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data07.ttl", format="TTL")
report = Report()

"""**TASK 7.1a:**

Spanish: Para todas las clases, enumera cada classURI. Si la clase pertenece a otra clase, indica su superclase. Realiza el ejercicio en RDFLib devolviendo una lista de tuplas: (clase, superclase) denominada "result". Si una clase no tiene superclase, devuelve None como superclase.

English: For all classes, list each classURI. If the class belogs to another class, then list its superclass. Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass
"""

# List every declared class and its direct superclass (None if there is none).
classes = set(g.subjects(RDF.type, RDFS.Class))
result = []
for c in sorted(classes, key=str):
    superclasses = sorted(g.objects(c, RDFS.subClassOf), key=str)
    if superclasses:
        result.extend((c, sc) for sc in superclasses)
    else:
        result.append((c, None))

# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b:**

Spanish: Repite el mismo ejercicio en SPARQL, devolviendo las variables ?c (clase) y ?sc (superclase)

English: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)
"""

# Return every class and its direct superclass; OPTIONAL preserves classes without one.
query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
ORDER BY ?c ?sc
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a:**

Spanish: Enumera todos los individuos de "Person" con RDFLib (ten en cuenta las subclases). Devuelve los URI de los individuos en una lista llamada "individuals".

English: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# Return all instances of Person, including instances of any transitive subclass.
person_classes = {ns.Person}
changed = True
while changed:
    changed = False
    for subclass, superclass in g.subject_objects(RDFS.subClassOf):
        if superclass in person_classes and subclass not in person_classes:
            person_classes.add(subclass)
            changed = True

individuals = sorted(
    {individual
     for cls in person_classes
     for individual in g.subjects(RDF.type, cls)},
    key=str
)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b:**

Spanish: Repite el mismo ejercicio en SPARQL, devolviendo los URI individuales en una variable ?ind.

English: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind
"""

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?ind
WHERE {
  ?ind a/rdfs:subClassOf* ns:Person .
}
ORDER BY ?ind
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:**

Spanish: Enumera el nombre y el tipo de quienes conocen a Curry (solo en SPARQL). Utiliza el nombre y el tipo como variables en la consulta.

English: List the name and type of those who know Curry (in SPARQL only). Use name and type as variables in the query
"""

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?name ?type
WHERE {
  ?entity ns:knows ns:Curry ;
          rdfs:label ?name ;
          a ?type .
}
ORDER BY ?name ?type
"""

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4:**

Spanish: Enumera los nombres de aquellas entidades que tengan un compañero de trabajo que tenga un perro, o que tengan un compañero de trabajo que tenga un compañero de trabajo que tenga un perro (en SPARQL). Devuelve los resultados en una variable llamada «name».

English: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name
"""

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?name
WHERE {
  {
    ?entity ns:hasColleague ?colleague .
    ?colleague ns:ownsPet ?dog .
    ?dog a ns:Animal .
  }
  UNION
  {
    ?entity ns:hasColleague ?colleague .
    ?colleague ns:hasColleague ?otherColleague .
    ?otherColleague ns:ownsPet ?dog .
    ?dog a ns:Animal .
  }
  ?entity rdfs:label ?name .
}
ORDER BY ?name
"""

for r in g.query(query):
  print(r.name)

# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")