# -*- coding: utf-8 -*-
"""Task09_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RXgg4CbyNMtmCoX6qGVeMOTsaxb8vnt

**Task 09: Data linking**
"""

# !pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Spanish: Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos.

English: Search for individuals in both graphs and link them using the OWL:sameAs property; insert these matches into g3. We consider two individuals to be the same if they have the same first name and surname. Please note that the URIs do not necessarily have to be the same for the same individual in both graphs.
"""

from rdflib.namespace import RDF, OWL

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

def get_profiles(graph):
    """
    Build a dictionary {person_uri: (given_name, surname)} with every
    individual in `graph` that has a vcard:Given property.
    The surname is None when the individual has no vcard:Family value.
    """
    profiles = {}
    for s in set(graph.subjects(VCARD.Given, None)):
        given = graph.value(s, VCARD.Given)
        family = graph.value(s, VCARD.Family)
        profiles[s] = (str(given).strip(),
                       str(family).strip() if family is not None else None)
    return profiles

profiles_g1 = get_profiles(g1)
profiles_g2 = get_profiles(g2)

# Two individuals are considered the same iff they share BOTH the first
# name (vcard:Given) and the surname (vcard:Family). Note that the URIs
# do not have to be equal for the same person in the two graphs.
for uri1, (given1, family1) in profiles_g1.items():
    if family1 is None:            # surname missing -> rule cannot be applied
        continue
    for uri2, (given2, family2) in profiles_g2.items():
        if family2 is not None and given1 == given2 and family1 == family2:
            g3.add((uri1, OWL.sameAs, uri2))   # insert the match into g3

# Show the resulting links
print(f"{len(g3)} owl:sameAs triples inserted into g3:\n")
for s, p, o in sorted(g3.triples((None, OWL.sameAs, None))):
    print(f"{s}  --sameAs-->  {o}")

# Sanity check: individuals that were NOT linked
print("\nIndividuals not linked:")
for uri, (given, family) in profiles_g1.items():
    if (uri, None, None) not in g3:
        print(f"  g1 {uri} (Given={given!r}, Family={family!r})")
for uri, (given, family) in profiles_g2.items():
    if (None, None, uri) not in g3:
        print(f"  g2 {uri} (Given={given!r}, Family={family!r})")