# -*- coding: utf-8 -*-
"""Task_06_completed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOWHaYkhKfEjDRyDQtq-abIGqMvckaq-

# **Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
# !pip install oeg-sw-class

"""Spanish: Importar la librería RDFLib

English: Import RDFLib main methods
"""

from rdflib import Graph, Namespace, Literal, URIRef, XSD
from rdflib.namespace import RDF, RDFS
from oeg_sw_class import Report
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Spanish: Crear una nueva clase llamada "Researcher"

English: Create a new class named Researcher
"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""### **Task 6.0:**

Spanish: Crea nuevos prefijos para "ontology", "organization" and "person", con la siguiente información:

*   person: http://oeg.fi.upm.es/resource/person/
*   organization: http://oeg.fi.upm.es/resource/organization/
*   ontology: http://oeg.fi.upm.es/def/people#

English: Create new prefixes for "ontology", "organization" and "person", with the following information:

*   person: http://oeg.fi.upm.es/resource/person/
*   organization: http://oeg.fi.upm.es/resource/organization/
*   ontology: http://oeg.fi.upm.es/def/people#
"""

# Create and bind the required namespaces
person       = Namespace("http://oeg.fi.upm.es/resource/person/")
organization = Namespace("http://oeg.fi.upm.es/resource/organization/")
ontology     = Namespace("http://oeg.fi.upm.es/def/people#")
university   = Namespace("http://oeg.fi.upm.es/resource/organization/")

g.bind("person", person)
g.bind("organization", organization)
g.bind("ontology", ontology)
g.bind("university", university)

"""### **Task 6.1**

Spanish: Reproduce la taxonomía de clases que aparece en el diagrama (`Assignment4/course_materials/diagram/diagram.jpg`). Añade etiquetas para cada una de ellas tal y como aparecen en el diagrama (exactamente), sin etiquetas de idioma. Recuerda añadir el tipo de datos correcto (xsd:String) cuando sea necesario.

English: Reproduce the taxonomy of classes shown in the diagram (`Assignment4/course_materials/diagram/diagram.jpg`). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate.

"""

# For convenience, add map of classes
classes = {
    "Person"                    : ontology.Person,
    "Professor"                 : ontology.Professor,
    "FullProfessor"             : ontology.FullProfessor,
    "AssociateProfessor"        : ontology.AssociateProfessor,
    "AssistantProfessor"        : ontology.AssistantProfessor,
    "InterimAssociateProfessor" : ontology.InterimAssociateProfessor,
}

# assign label for each class
for label, cls in classes.items():
    g.add((cls, RDF.type, RDFS.Class))
    g.add((cls, RDFS.label, Literal(label, datatype=XSD.string)))

# construct parent & child class hierarchy
for child, parent in [
    (ontology.Professor, ontology.Person),
    (ontology.FullProfessor, ontology.Professor),
    (ontology.AssociateProfessor, ontology.Professor),
    (ontology.AssistantProfessor, ontology.Professor),
    (ontology.InterimAssociateProfessor, ontology.AssociateProfessor),
]:
    g.add((child, RDFS.subClassOf, parent))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_01(g)

"""### **Task 6.2**

Spanish: Crea la clase ontology:University.

English: Create the ontology:University class.
"""

# University class
g.add((ontology.University, RDF.type, RDFS.Class))
g.add((ontology.University, RDFS.label, Literal("University", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_02(g)

"""### **Task 6.3**

Spanish: Añade las propiedades que aparecen en el diagrama. Añade etiquetas para cada una de ellas (exactamente como aparecen en la diapositiva, sin etiquetas de idioma), así como sus dominios y rangos correspondientes utilizando RDFS. Recuerda añadir el tipo de datos correcto (xsd:String) cuando sea necesario. Si una propiedad no tiene rango, conviértela en un literal (cadena de caracteres). Por otra parte, ontology:affiliatedWith tendrá como dominio ontology:Person y rango ontology:University.

English: Add the properties shown in the previous diagram. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string). Furthermore, the ontology:affiliatedWith property will have ontology:Person as its domain and ontology:University as its range.

"""

# Properties, labels, domains and ranges
properties = {
    ontology.hasName        : ("hasName", ontology.Person, RDFS.Literal),
    ontology.hasColleague   : ("hasColleague", ontology.Person, ontology.Person),
    ontology.hasHomePage    : ("hasHomePage", ontology.FullProfessor, RDFS.Literal),
    ontology.affiliatedWith : ("affiliatedWith", ontology.Person, ontology.University),
}

for prop, (label, domain, range_) in properties.items():
    g.add((prop, RDF.type, RDF.Property))
    g.add((prop, RDFS.label, Literal(label, datatype=XSD.string)))
    g.add((prop, RDFS.domain, domain))
    g.add((prop, RDFS.range, range_))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_03(g)

"""### **Task 6.4**

Spanish: Crea los individuos que aparecen en el diagrama, en la sección «Datos». Vincúlalos con las mismas relaciones que se muestran en el diagrama.

English: Create the individuals shown in the diagram under "Datos". Link them with the same relationships shown in the diagram."
"""

# Individuals and relationships shown in the data diagram
university = Namespace("http://oeg.fi.upm.es/resource/university/")
g.bind("university", university)

'''
schema
 key - (role, colleagues_list, institution, home_page, name)
'''
faculties = {
    "Raúl"  : (ontology.FullProfessor,      ["Juan"], None, "http://www.garcia-castro.com/", None),
    "Juan"  : (ontology.AssistantProfessor, ["Sven"], None, None, "Juan Cano de Benito"),
    "Sven"  : (None, [], university.Manheim, None, None),
}

for label, (role, colleagues_list, institution, home_page, name) in faculties.items():
    # resolve to person entity
    faculty = URIRef(person[label])

    # add role to person entity
    if role is not None:
        g.add((faculty, RDF.type, role))

    # add colleague to person entity
    for colleague in colleagues_list:
        g.add((faculty, ontology.hasColleague, URIRef(colleague)))

    # add institution to person entity
    if institution is not None:
        g.add((faculty, ontology.affiliatedWith, URIRef(university[institution])))

    # add home page to person entity
    if home_page is not None:
        g.add((faculty, ontology.hasHomePage, Literal(home_page, datatype=XSD.string)))

    # add name to person entity
    if name is not None:
        g.add((faculty, ontology.hasName, Literal(name, datatype=XSD.string)))

    # add label to person entity
    g.add((faculty, RDFS.label, Literal(label, datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_04(g)

"""### **Task 6.5**

Spanish: Añadir a person:Juan la dirección email (juan.cano@upm.es), el nombre (given) y los apellidos (family). Utiliza las propiedades que ya se incluyen en el ejemplo 4 para describir a Jane y John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). No importes los espacios de nombres; añádelos manualmente.

English: Add to the individual person:Juan the email address (juan.cano@upm.es), given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually.

"""

foaf = Namespace("http://xmlns.com/foaf/0.1/")
g.bind("foaf", foaf)

# Add Juan's FOAF properties
g.add((person.Juan, foaf.mbox, URIRef("mailto:juan.cano@upm.es")))
g.add((person.Juan, foaf.givenName, Literal("Juan", datatype=XSD.string)))
g.add((person.Juan, foaf.familyName, Literal("Cano de Benito", datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_05(g)

"""### **Task 6.6**

Spanish: Añade que Juan y Raúl están afiliados (affiliatedWith) a university:UPM. También que Sven es de tipo InterimAssociateProfessor.

English:  Add that Juan and Raúl are affiliated (affiliatedWith) with the university:UPM. Also add that Sven is a InterimAssociateProfessor
"""

# Affiliation and additional type
g.add((person.Juan, ontology.affiliatedWith, university.UPM))
g.add((person.Raul, ontology.affiliatedWith, university.UPM))
g.add((person.Sven, RDF.type, ontology.InterimAssociateProfessor))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_06(g)

"""### **Task 6.7**

Spanish: Tanto university:UPM como university:Mannheim son de tipo ontology:University.

English:  Both university:UPM and university:Mannheim are ontology:University type.
"""

# University individuals
g.add((university.UPM, RDF.type, ontology.University))
g.add((university.Mannheim, RDF.type, ontology.University))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

#Validation: Do not remove
r.validate_task_06_07(g)
r.save_report("_Task_06")